### PR TITLE
Fix Regex needle for multi-line strings

### PR DESCRIPTION
**Pull request by andymbody**
Fix Regex needle for multi-line strings - making it 4-5 times more efficient than before.
Also fix lineS in _SendMessage() of 1Commands.ahk (missing CRLFs).

### CODE REVIEW

**Comment by mmikeww** [comment]
dont forget to add a new test that displays what this fix fixes

**Comment by andymbody** [comment]
> dont forget to add a new test that displays what this fix fixes

How do I show a fix for efficiency? The needle before took 5 times as long to get the same result. The prior needle used very slow lazy quantifiers, I changed it to be greedy, yet possessive to process each line one at a time in chunks (instead of looking at every single character one at a time. Less of a bug, and more of a performance boost.

**Comment by mmikeww** [comment]
oh ok gotcha, just mention that in the PR text or commit message then, so people can understand why the change is being made

**Comment by andymbody** [comment]
Added fix for lines in _SendMessage() (missing CRLFs). I wonder why no error was generated.

**Comment by andymbody** [comment]
Apparently I messed the file up when I tried to fix typo... removing PR and will fix and resubmit

**Pull request closed without merging**
