### PR TITLE
Updated String and string masking Support

### PR DESCRIPTION
**Pull request by andymbody**
Updated string mask needle for better support, ToExp(), ToStringExp(), Fixed MsgBox_ex7. Hopefully I did this correctly this time (using bash command line).

### CODE REVIEW

**Comment by Banaanae** [comment]
Looks good, Ill test when I get home

**Comment by mmikeww** [comment]
would like to see new tests proving why to even make these changes... if its just a pure refactor thats fine, but you should say that if so. if these changes enable new features that were previously missing, should add tests demonstrating that

**Comment by andymbody** [comment]
> would like to see new tests proving why to even make these changes... if its just a pure refactor thats fine, but you should say that if so. if these changes enable new features that were previously missing, should add tests demonstrating that

The regex needle within the string masking function that was submitted a few months ago was not meant to support all stings. As I recall, it was a quick edit that I planned to change in my next submission. But, I ran into an obstacle with submitting pull requests because I could not log into github using bash command line tool (would not accept my password). And I was (still am) unfamiliar with the proper commands using that tool. This caused a delay for me to submit these changes until I became more familiar with submissions. I finally managed to get connected using the command line tool, so I submitted this change last night (after months of delay).

The ToExp() and ToStringExpr() would not allow test MsgBox_ex7 to succeed, so I made the edit to those functions. Which yes, is also a refactoring/restructuring (and added comments) to make it more clear what is taking place in those functions.

I have no new tests to submit, but did move MsgBox_ex7 from the failed section, to the successful section in test folders. Should we not be attempting to fix broken tests? Then moving those tests once they are fixed?

Thanks,
Andy

**Comment by Banaanae** [comment]
> but did move MsgBox_ex7 from the failed section, to the successful section in test folders. Should we not be attempting to fix broken tests? Then moving those tests once they are fixed?

This is what we do, please continue to fix these tests if you know how :)


I've ran these changes and runs smoothly, I'm willing to merge

<sub>
pattern := '(*UCP)`'`'|`'([^`'\v]+(?:(?<=``)`')?)+`'|""|"([^"\v]+(?:(?<=``)")?)+"'


Great regex work :)
</sub>

**Comment by andymbody** [comment]
> would like to see new tests proving why to even make these changes... if its just a pure refactor thats fine, but you should say that if so. if these changes enable new features that were previously missing, should add tests demonstrating that

The regex needle within the string masking function that was submitted a few months ago was not meant to support all stings. As I recall, it was a quick edit that I planned to change in my next submission. But, I ran into an obstacle with submitting pull requests because I could not log into github using bash command line tool (would not accept my password). And I was (still am) unfamiliar with the proper commands using that tool. This caused a delay for me to submit these changes until I became more familiar with submissions. I finally managed to get connected using the command line tool, so I submitted this change last night (after months of delay).

The ToExp() and ToStringExpr() would not allow test MsgBox_ex7 to succeed, so I made the edit to those functions. Which yes, is also a refactoring/restructuring (and added comments) to make it more clear what is taking place in those functions. The generic loop within those functions was difficult for me to follow, so I started from scratch with the edit (using regex). Once it was working for MsgBox_ex7, I simply left it that way., and submitted the changes with those edits.

I have no new tests to submit, but did move the failing MsgBox_ex7 from the failed section, to the successful section in test folders. The edits I made fixed this case. Should we not be attempting to fix broken tests? Then moving those tests once they are fixed? Are more test also required when a previously broken test is fixed?

I'm trying to concentrate on edits for string support at the moment before moving on to other failed tests such as regex, menu, etc. IMO, concentrating on one type of failure/fix at a time works best (in my mind), rather than bouncing around multiple types of unrelated edits. It just makes sense to me this way.

Thanks,
Andy

**Comment by andymbody** [comment]
> would like to see new tests proving why to even make these changes... if its just a pure refactor thats fine, but you should say that if so. if these changes enable new features that were previously missing, should add tests demonstrating that

The regex needle within the string masking function that was submitted a few months ago was not meant to support all stings. As I recall, it was a quick edit that I planned to change in my next submission. But, I ran into an obstacle with submitting pull requests because I could not log into github using bash command line tool (would not accept my password). And I was (still am) unfamiliar with the proper commands using that tool. This caused a delay for me to submit these changes until I became more familiar with submissions. I finally managed to get connected using the command line tool, so I submitted this change last night (after months of delay).

The ToExp() and ToStringExpr() would not allow test MsgBox_ex7 to succeed, so I made the edit to those functions. Which yes, is also a refactoring/restructuring (and added comments) to make it more clear what is taking place in those functions. The generic loop within those functions was difficult for me to follow, so I started from scratch with the edit (using regex). Once it was working for MsgBox_ex7, I simply left it that way., and submitted the changes with those edits.

I have no new tests to submit, but did move the failing MsgBox_ex7 from the failed section, to the successful section in test folders. The edits I made fixed this case. Should we not be attempting to fix broken tests? Then moving those tests once they are fixed? Are more test also required when a previously broken test is fixed?

I'm trying to concentrate on edits for string support at the moment before moving on to other failed tests such as regex, menu, etc. IMO, concentrating on one type of failure/fix at a time works best (in my mind), rather than bouncing around multiple types of unrelated edits. It just makes sense to me this way.

I'm also trying to follow your guideline of "one fix, one pull request". At least this is how I understood it... did I misunderstand?

Thanks,
Andy

**Comment by mmikeww** [comment]
my mistake! i didnt see the msgbox7 example since there was no changes to the file, it was just moved. 

and yes, one fix per pull request. with the tests accompanying the fix

**Comment by andymbody** [comment]
> i didnt see the msgbox7 example
> and yes, one fix per pull request. with the tests accompanying the fix

Ok... thanks for the clarification.

**Comment by andymbody** [comment]
> This is what we do, please continue to fix these tests
Ok... thank you.

> I've ran these changes and runs smoothly,
Thanks for the update

> Great regex work
Should cover most if not all quoted strings, with single or double quotes v1 or v2. Let me know if this is not the case and tweaks will be made.

**Comment by andymbody** [comment]
> This is what we do, please continue to fix these tests
>
Ok... thank you.

> I've ran these changes and runs smoothly,
>
Thanks for the update

> Great regex work
>
Should cover most if not all quoted strings, with single or double quotes v1 or v2. Let me know if this is not the case and tweaks will be made.

**Comment by andymbody** [comment]
FYI... wanted to mention that string masking does not currently support multiline (continuation) strings. That is planned tho... maybe this week. Have not started the needle design yet. Should be fairly easy to mask those blocks if needed. Other continuation sections may be trickier, but also planned as part of the masking suite. They will not be included in the global masking, but will be available as needed.

**Pull request merged**
