### PR TITLE
Fix for (multiple) keyword removal/replacements affecting strings

### PR DESCRIPTION
**Pull request by andymbody**
This is to prevent strings from being changed when processing keywords such as Clipboard and New. Full list so far also includes A_BatchLines, A_isUnicode, A_LoopFileFullPath, A_LoopFileLongPath, A_NumBatchLines, ClipboardAll, ComObjParameter, ComSpec. Should apply to Issue  #115 (from Lexikos). I added a couple functions that can be used when other keywords require the same treatment. This can be done very easily as follows. 

1. Mask the line strings (treats each string separately)
2. Process the keyword
3. Restore the line strings

Oh... btw... I'm not sure whether my edit messed up the unicode characters within ConvertFuncs, compared to the original. I forgot to convert to UTF-8 BOM prior to committing the edit. The edits to the existing unicode masks was unintentional. Please look at this... Thanks. Let me know if I need to resubmit without these accidental edits.

### CODE REVIEW

**Comment by Banaanae** [comment]
> unicode characters within ConvertFuncs

All the changes are all the same across each instance, it'll be fine (if anything now its more unlikely for code to accidentally contain them)


You might notice I added commit [`4d69d06`](https://github.com/mmikeww/AHK-v2-script-converter/pull/156/commits/4d69d067118d560030d8b465ba6be0495235acb3)
This fixes the trailing newlines causes tests to error (which I think github editor adds by default, thanks github)


Other than that your changes look good, but I'll wait for mike to review since most of them go right over my head :)

**Comment by andymbody** [comment]
> All the changes are all the same across each instance, it'll be fine (if anything now its more unlikely for code to accidentally contain them)
Ok... that works for me, but if (at some point) I need to fix the accidental edit of unicode within existing masks, let me know.

> You might notice I added commit [`6cd8381`] This fixes the trailing newlines causes tests to error (which I think github editor adds by default, thanks github)
I did not notice any errors, but I will try to watch for this going forward.

> Other than that your changes look good, but I'll wait for mike to review since most of them go right over my head :)
Ok... sounds good. I'm going to wait for the merge (if he approves) before submitting the edits to correct other issues. I am also working on a major edit that may or may not be welcome because I have identified some issues with a section of code because it does not take into account nested commands. This leads to many failures. I feel a different approach is required to accommodate nested commands.

**Comment by andymbody** [comment]
> All the changes are all the same across each instance, it'll be fine (if anything now its more unlikely for code to accidentally contain them)
>
Ok... that works for me, but if (at some point) I need to fix the accidental edit of unicode within existing masks, let me know.

> You might notice I added commit [`6cd8381`] This fixes the trailing newlines causes tests to error (which I think github editor adds by default, thanks github)
>
I did not notice any errors, but I will try to watch for this going forward.

> Other than that your changes look good, but I'll wait for mike to review since most of them go right over my head :)
>
Ok... sounds good. I'm going to wait for the merge (if he approves) before submitting the edits to correct other issues. I am also working on a major edit (that may or may not be welcome) that will hopefully address nested commands. The current code does not seem to accommodate this, and as you know, nested commands can be a regular occurrence. I feel that a different approach is required to handle nested/chained commands.

**Comment by mmikeww** [comment]
couple things for @andymbody 

i like to propose using the TDD method when possible, which is where you first write some new test cases that would FAIL with the current code. that way we can see what is being proposed. and then add the commits that would enable the new tests to PASS. 

so here, instead of overwriting/updating the existing tests to add the word "new" inside a string, just create new test files and name them appropriately. not a big deal at all in this case, but just a thought i had. and on the other hand, modifying the "clipboard' tests is obviously correct since those existing tests had been broken. and as you can see @Banaanae had to add fixes for newlines because the tests were failing. before you submit your PR you should run the full test suite to ensure no tests are broken. 

second, you dont need to create individual commits for each file. you can add all files that you update in a single commit. i probably wouldve broken up the changes a bit differently but this is quite fine for your first PR. but therefore, i think when we merge this PR, we should use the 'squash' method which will merge all of these individual commits into a single commit.

and @Banaanae 

> Other than that your changes look good, but I'll wait for mike to review since most of them go right over my head :)

the beauty of having the test suite is that even if we dont fully understand the changes, as long as the entire test suite passes, then we know the converter should be good. this is why the test suite is so important. of course its also extra tedious work, but as new people contribute bigger features, it becomes an essential benchmark to ensure no old functionality gets broken. but of course we should understand the changes before blindly merging.

**Comment by mmikeww** [comment]
@andymbody 

> Oh... btw... I'm not sure whether my edit messed up the unicode characters within ConvertFuncs, compared to the original. I forgot to convert to UTF-8 BOM prior to committing the edit. The edits to the existing unicode masks was unintentional. Please look at this... Thanks. Let me know if I need to resubmit without these accidental edits.

i could do this but ill let you have the practice. try this from git bash commandline (or see if your tool has equivalents):

```
# move to your PR branch
git checkout replacements-affecting-strings

# ensure youre on the right branch by inspecting history in gui
gitk

# creates a new commit undoing the Update ConvertFuncs.ahk commit using its hash id
git revert aac08ad

# undos this new commit and but keeps the changes on the file system in a not-yet-committed state
git reset HEAD~1

# adds the file to staging area to be committed, but allows you to choose which parts to commit
git add --patch ConvertFuncs.ahk

# go through and hit 'n' to omit all of your new changes that we want to keep, but hit 'y' for the unicode
# placeholder sections that were accidentally edited

# commit the changes
git commit -m "fix accidental unicode edits"

# discard all the other revisions that we dont want to keep
git restore ConvertFuncs.ahk

# push this new commit to the PR branch
git push
```

**Comment by Banaanae** [comment]
I'll wait for if @andymbody  will want to make these changes (you`ll probably need `git push --force` as you're rewriting history)

All tests pass and I haven't found anything that fails from these changes (I also somewhat understand the changes now :D ) so I'm willing to merge

**Comment by Banaanae** [comment]
What's the reason for closing?

**Comment by andymbody** [comment]
> What's the reason for closing?

I think I had trouble submitting the PR properly (still learning), so I removed my attempt completely until I am able to do it properly. Other projects are keeping me from dedicating time to learning git/github which has become a barrier to submitting other suggested fixes as well. One of these days I will be up to speed, but not yet.

**Pull request closed without merging**
