### PR TITLE
Conversion menu - Fix lines that can't be done in main loop

### PR DESCRIPTION
**Pull request by Banaanae**
All below fixes must be done manually

# Fixes
- Add `MinIndex()` and `MaxIndex()` to arrays and maps (#178)

# Todo
- Turning off OnMessage in 99% of cases (implemented but buggy) (#136)
- Win* Exceptions (#100)
- Add menu to scintilla (done when all other todo items are finished)
- Figure out how to do tests

Not sure if this will end up being merged in this state, Min/MaxIndex and Win* exceptions aren't exactly what the script is about...
OnMessage is, but can't run in the main loop (Always possible to put it in after the main loop)

Tests will show up as failing regardless of whether they actually are, best solution would probably be to make another folder like Failing Tests, or figure out how to run those functions during testing.

### CODE REVIEW

**Comment by andymbody** [comment]
I think the code in this fix is the version that caused incorrect values. Check here for an update that should be correct
[Corrected code](https://github.com/mmikeww/AHK-v2-script-converter/issues/178#issuecomment-2155688795)

**Comment by andymbody** [comment]
Do you think the Map() version (with previous code) should be included?

**Comment by Banaanae** [comment]
Closing in favour of work done to fix #136 

I'll make an update in discussion soon about what to do with these edge cases

**Comment by Banaanae** [comment]
Won't delete this branch incase in the future it might be useful

**Pull request closed without merging**
