### PR TITLE
User defined var names conflict with v2 built-in var names

### PR DESCRIPTION
**Pull request by samfisherirl**
Hi Mike,

I hope this message finds you doing well. I wanted to check in on my previous outreach from a week ago and express my interest in connecting with you. I believe it was through autohotkey.com's forum, but I'm not entirely sure. I love your solution and integrated it with my app listed below.

I've been modifying the converter code to minimize runtime errors for output GUI. I think my changes could be valuable contributions to your repository. However, I'm in need of guidance on how to navigate the regex versus instr mods.

If you're available, I'd be happy to share what I've done so far and discuss further. Please let me know your availability, and we can take it from there. I have pushed my code as evidence of my work but it is not for integration into the project.

Thank you for your time, and I look forward to hearing from you soon. 

Best regards,
Sasha

https://github.com/samfisherirl/Auto-GUI-for-AHK-v2

# Example 3 ways

<h2> First, original code. Second, your conversion. Third, my modded output. </h2>

Code before conversion:

```autohotkey
Gui Font, s9, Segoe UI
Menu FileMenu, Add, &Open...`tCtrl+O, MenuHandler
Menu FileMenu, Icon, &Open...`tCtrl+O, shell32.dll, 4
Menu FileMenu, Add, Select &All`tCtrl+A, MenuHandler
Menu MenuBar, Add, &File, :FileMenu
Gui Menu, MenuBar

Gui Add, Button, x172 y78 w80 h23, &OK
Gui Add, CheckBox, x344 y136 w120 h23, CheckBox
Gui Add, Edit, x96 y168 w120 h21
```

<h3>Code converted by your application => naming errors:</h3>

```autohotkey

myGui := Gui()
myGui.OnEvent("Close", GuiEscape)
myGui.OnEvent("Escape", GuiEscape)
FileMenu := Menu()
FileMenu.Add("Select &All`tCtrl+A", MenuHandler)
MenuBar := Menu() ; <= ERROR
MenuBar.Add("&File", FileMenu)
FileMenu.Add("&Open...`tCtrl+O", MenuHandler)
MenuBar.Add("&File", FileMenu)
myGui.MenuBar := MenuBar

ogcButtonOK := myGui.Add("Button", "x172 y78 w80 h23", "&OK")
ogcButtonOK.OnEvent("Click", ButtonOK.Bind("Normal"))
myGui.Add("CheckBox", "x344 y136 w120 h23", "CheckBox")
myGui.Add("Edit", "x96 y168 w120 h21")

myGui.Title := "Window"
myGui.Show("w620 h400")
Return

MenuHandler(A_ThisMenuItem, A_ThisMenuItemPos, MyMenu)
{ ; V1toV2: Added bracket
Return
} ; V1toV2: Added bracket before function

```

My modifications:

```autohotkey
FileMenu := Menu()
FileMenu.Add("&Open...`tCtrl+O", MenuHandler)
FileMenu.Add("&Open...`tCtrl+O", MenuHandler)
FileMenu.Icon("&Open...`tCtrl+O", "shell32.dll", "4")
MenuBar_Storage := MenuBar()
MenuBar_Storage.Add("&File", FileMenu)
myGui := Gui()
myGui.MenuBar := MenuBar_Storage
ogcButtonOK := myGui.Add("Button", "x33 y37 w80 h23", "&OK")
ogcButtonOK.OnEvent("Click", ButtonHandler)
Edit_Storage1 := myGui.Add("Edit", "x214 y140 w120 h21")
Edit_Storage2 := myGui.Add("Edit", "x130 y104 w120 h21")
myGui.Title := "Window"
myGui.Show("w620 h400")
Return

MenuHandler(Item, *)
{
	ToolTip "Click! This is a sample action, you clicked  ==> a menu item.`n" Item, 20, 20
	SetTimer () => ToolTip(), -2000 ; timer expires in 2 seconds and tooltip disappears
}

ButtonHandler(*)
{

    string := "Click! This is a sample action, you clicked  ==> a button. `nThe edit values include:"
    string .= "`n //Value 1// " Edit_Storage1.Value "`n //Value 2// " Edit_Storage2.Value
    ToolTip string, 20, 20
} 

```

### CODE REVIEW

**Comment by mmikeww** [comment]
Sadly I have not kept up with development of this converter, so I cannot give you much help on guidance on structure. Most of the newer work has been done by @dmtr99 (AHK_user on the forums), and he has made some significant updates which I'm not familiar with.

That said, I initially built this off some previous works, and my goal was to make it easy for other people to contribute additions just like you are proposing. This converter is fairly complex though. And so we don't want to break previous work. That's why I was so strongly persistent about writing the test cases. That way people can test additions, click a button to run all tests, and make sure everything still works. Writing the unit tests is tedious work, but its so so so important nonetheless.

So I would prefer that you add the appropriate unit test code with any Pull Request as well, so people have a concrete example of what the proposed change is trying to accomplish.

Its also preferable to keep updates as small and isolated as possible. So for example, with what you've provided, can the bug be re-created with this simpler starting code?

```
Menu FileMenu, Add, &Open...`tCtrl+O, MenuHandler
Menu FileMenu, Icon, &Open...`tCtrl+O, shell32.dll, 4
Menu FileMenu, Add, Select &All`tCtrl+A, MenuHandler
Menu MenuBar, Add, &File, :FileMenu
```

Or even smaller? If so, thats how the changes are ideally proposed, and the unit test code can include this simpler version

Ultimately I like that this converter become a community project. It usually grows via the motivation of an individual. I originally had that motivation, which led me to create this. Then @dmtr99 had his own motivation and pretty much solely picked up development by himself. Perhaps you have the motivation to take the lead next.

**Comment by mmikeww** [comment]
Ah so this bug is not actually related to `Menu` conversion, but rather when v1 code has used user defined variables which were named the same as v2 built in variables.

Are you saying that if we always add a suffix (maybe not "_storage" maybe "_var", but it doesnt really matter I guess) then that would solve the problem?

If so, from a quick browse, it looks like the menu name is pulled out in this line:

https://github.com/mmikeww/AHK-v2-script-converter/blob/c003ebb6a3314e81f18f385f6f21648ea259a9a0/ConvertFuncs.ahk#L2135

The variable is named poorly. It shouldn't be "menuNameLine" but rather simply "menuName". 

But if you think adding a suffix would fix it, we could do it right after that..

**Comment by dmtr99** [comment]
There is a possibility that this could create other problems, so I would not implement it all the time, only if required. 
Add a check if the name is conflicting with the v2 rules.

The same conversion error could apply to all the conversions...

In my opinion this does not has high priority, as the error is exceptional and easy to fix.

**Comment by samfisherirl** [comment]
> Ah so this bug is not actually related to `Menu` conversion, but rather when v1 code has used user defined variables which were named the same as v2 built in variables.
> 
> Are you saying that if we always add a suffix (maybe not "_storage" maybe "_var", but it doesnt really matter I guess) then that would solve the problem?
> 
> If so, from a quick browse, it looks like the menu name is pulled out in this line:
> 
> https://github.com/mmikeww/AHK-v2-script-converter/blob/c003ebb6a3314e81f18f385f6f21648ea259a9a0/ConvertFuncs.ahk#L2135
> 
> The variable is named poorly. It shouldn't be "menuNameLine" but rather simply "menuName".
> 
> But if you think adding a suffix would fix it, we could do it right after that..

@dmtr99 

You guys got it. It's when variables conflict with built in variables. I think how we would go about fixing may be not worth the trouble and it does appear to be wider than I initially thought, not just menu's. 

I'm going to stick with Menu as an example as I do not immediately know where else this would or wouldn't be applicable. A fixed would need to check if and only if assigning a Variable to a Built in Variable. What is appended to the variable name is inconsequential, but necessary to fix to clear the issue.

I went through the AHKv1 documentation, all menu variables get explicit names such as "MyMenu" fixing the conversion issue. Where with my app mods, Easy AutoGUI uses specifically "Menu" and "MenuBar" as the _name_ of the MenuBar. I have accounted for that in my code, so its not an issue for me specifically. If its also seen as a hyper specific use case and unnecessary I can probably agree, I just haven't spent enough time in other areas to get a feel for the scope.

**Comment by mmikeww** [comment]
1. Before we could even begin to tackle the problem of user defined variables conflicting with built-in variables, we'd need to start compiling a list of all new v2 biult-in var names. Does such a list exist anywhere? 

2. As for the Bind error, thats not actually a problem with syntax conversion, but rather with the name of the original button text being ">" which is not valid as a variable name.

3. Your MenuHandler placeholder seems fine

But lets keep each github issue related. 2 and 3 are different topics so start new threads or pull requests if you build the fixes. You are free to take the liberty on the design. Just make sure you include the individual tests. It looks like we only have one large GUI control test, which I'm not a fan of. I would rather see each individual test be broken down smaller.

**Comment by Lexikos** [comment]
The most reliable list of built-in variables is the one used by AutoHotkey itself, in [g_BIV_A](https://github.com/AutoHotkey/AutoHotkey/blob/e18a857e2d6d57d73643fbdd57d739a88ea499e5/source/script.cpp#L155) (this link is for v2.1-alpha.1).

The issue with menu names is neither specific to built-in variables nor specific to menus.

When you introduce new variables to the script, you must ensure that there aren't already variables with those names. This includes user-defined variables. Menu and Gui names in v1 are in their own "namespaces", so if you directly move them into the global namespace, you may create conflicts.

A very simple scheme is to include an uncommon prefix (perhaps utilizing non-ASCII characters) that is obvious to the user and likely to be unique. The user can remove or replace the prefix at their leisure.

The Menu and Gui "variables" don't need to be variables as such; they could be properties stored in a class/object defined by the converter, or directly in `Menu` or `Gui` (but in that case you must avoid conflicts with predefined static methods and classes). If you use properties of a global object, you need not be concerned with global declarations.

Note that if the code is inside a function, `MenuBar := Menu()` will not produce an error unless you have declared `global MenuBar`. However, it would implicitly define a local variable which shadows the built-in class, making it difficult to create a MenuBar inside the function.

Also note that assigning a menu created with `Menu()` to `myGui.MenuBar` is not valid. Menu bars must be created with `MenuBar()`, not `Menu()`.

**Pull request closed without merging**
