### PR TITLE
Create issue templates

### PR DESCRIPTION
**Pull request by Banaanae**
Created an issue template to *hopefully* make receiving issues more comprehensive.

### CODE REVIEW

**Comment by Banaanae** [comment]
If [issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) would be preferred please let me know

**Comment by mmikeww** [comment]
looks fine imo!

**Comment by andymbody** [comment]
Curious... how is his template initiated by a user?

**Comment by andymbody** [comment]
Clarification... how is his template initiated by a user? Will this be used automatically by Github when someone initiates an issue? I read that there are also pull request templates that can be included (if I understood it correctly).

**Comment by andymbody** [comment]
Clarification... how is this template initiated by a user? Will this be used automatically by Github when someone initiates an issue? I read that there are also pull request templates that can be included (if I understood it correctly).

**Comment by Banaanae** [comment]
> Clarification... how is this template initiated by a user? Will this be used automatically by Github when someone initiates an issue? I read that there are also pull request templates that can be included (if I understood it correctly).

When the user presses the new issue button it comes up with a list, conversion error and blank issue. Blank issue is just what currently happens, while selecting Conversion Error will have 3 code boxes, for V1, V2 and v2e. This should hopefully encourage users to share their script and the error.

Pull request templates do exist but I have created any (not *as* necessary)

**Comment by andymbody** [comment]
Thanks for the feedback Banaanae

**Pull request merged**
