### PR TITLE
Fix A_IPAddress

### PR DESCRIPTION
**Pull request by Banaanae**
This should fix A_IPAddress1 to 4, but I can't test because of https://www.autohotkey.com/boards/viewtopic.php?f=14&t=127416
If someone could run `A_IPAddress_ex1.ah2` to make sure if behaves correctly so it can safely merge?

### CODE REVIEW

**Comment by andymbody** [comment]
I was able to run your suggested code successfully but if there is no IP to be captured, the code produces an empty element error. V1 would return a null string of course, but v2 doesn't like accessing invalid array elements. Doesn't seem like the converter should become responsible for overcoming that condition tho, right?

**Comment by andymbody** [comment]
By the way... what happens to old PR like this one when many more changes/merges have been made to the project? If this was to be merged now, would it be done smoothly despite all the changes that came before it? It seems to me that the project would get out of sync since this PR has older code. Is that the case or is able to overcome this somehow?

**Comment by mmikeww** [comment]
> By the way... what happens to old PR like this one when many more changes/merges have been made to the project? If this was to be merged now, would it be done smoothly despite all the changes that came before it? It seems to me that the project would get out of sync since this PR has older code. Is that the case or is GIT able to overcome this somehow?

yes you are correct that the project would be out of sync, since his PR branch Banaanae:fix-A_IPAddress  is 45 commits behind the tip of the main branch here (you can click the link at the top)

in git, what you need to do is 'rebase' the work branch onto the main branch. what this does is replays all the new work commits on top of the tip of the main branch, and then prompts you to fix all of the conflicts that might arise. you can see that github even shows us that there are conflicts that need to be resolved

you could test this locally if you wanted to on a throwaway test branch and test out the process. i'm not sure how SourceGit handles it. but youll want to pull from Banaanae's branch `fix-A_IPAddress` and then rebase that onto the master branch, and see what prompts you get

**Comment by andymbody** [comment]
> yes... you could test this locally if you wanted to on a throwaway test branch

Ok... will try that... thanks for the details!

**Comment by Banaanae** [comment]
> I was able to run your suggested code successfully but if there is no IP to be captured, the code produces an empty element error. V1 would return a null string of course, but v2 doesn't like accessing invalid array elements. Doesn't seem like the converter should become responsible for overcoming that condition tho, right?

I think it should be left as is, if the user needs wants the old functionality they can use a try catch block or [this](https://github.com/mmikeww/AHK-v2-script-converter/issues/100#issuecomment-1846244090) style of function override

I'll update this fork and merge the changes

**Pull request closed without merging**
