### PR TITLE
Update ConvertFuncs.ahk

### PR DESCRIPTION
**Pull request by andymbody**
Fix for accidental typos that were made in last PR #164 Also updated mask vars and regex

### CODE REVIEW

**Comment by mmikeww** [comment]
If these changes are still part of #164 then you should just add the commit
to that PR branch

**Comment by andymbody** [comment]
Ok... ( I think... lol). This is all very confusing to me because I am bouncing in and out of different repositories that all look the same unless I drill down into different files. I have better fix for #163 since that was just a quick patch until I submit the better fix. So maybe both #163 and #164 should be rejected, since those changes will be replaced in my next commit anyway.

**Comment by mmikeww** [comment]
Pull Requests simply track specific branches from your personal github repository

if you want to create new changes based off of your previous work, you could create a new branch off your existing PR branch. or, since really its the same logical change, just different versions, you could just stay on the same branch and just keep adding new commits. 

for example, you created a new branch `patch-1` for this PR. but you probably shouldnt have done that. you shouldve just continued work on the branch for PR #164 which it looks like you named that branch `Fix-issue-#163`. so any new commits you pushed to that branch on your github would be tracked in the #164 PR

**Comment by andymbody** [comment]
I'm curious... would it be easier for everyone if I were to create a new ahk file that could be #included instead of adding all the changes to ConvertFunc? The new file would be my functions that I am in the process of updating. That way there is minimal changes required to ConvertFunc. And if I make a change to the new function file, it will not affect pull requests from other contributions, since most will not be updating code that I am contributing. Do you know what I mean?

**Comment by andymbody** [comment]
Retracted. Will do this another time

**Comment by mmikeww** [comment]
Up to you really. There isn't many competing pull requests at the moment so
it's not a big deal for you to edit the main file

**Pull request closed without merging**
