### PR TITLE
Normalise Exts

### PR DESCRIPTION
**Pull request by fade2gray**
For clarity within the source, consider using the ah1 ext for all v1 code, and the ah2 ext for all v2 code. This also helps with some compatibility issues with some of the extensions/addons of particular IDEs.

1. Replace \diff\VisualDiff.exe (v1.1.24.01 is 8yrs old) with latest AutoHotkeyU64.exe (currently v1.1.37.02). This allows \diff\VisualDiff.ahk to be headed with "#Requires AutoHotkey v1.1" without causing an error when viewing the diffs with QuickConverterV2.ahk and v2converter.ahk.
2. Head \diff\VisualDiff.ahk with "#Requires AutoHotkey v1.1"
3. In \diff\VisualDiff.ahk, replace `"_AHKv1v2_\d{10}\.ahk$"` with `"_AHKv1v2_\d{10}\.(ahk)|(ah1)$"`, otherwise, if srcFilePath has an ah1 extension, it won't be deleted on exit.
4. In \diff\VisualDiff.ahk, replace FileObject.ahk, WB_onKey.ahk and API.ahk, with FileObject.ah1, WB_onKey.ah1 and API.ah1 respectively.
5. Rename \diff\VisualDiff.ahk to \diff\VisualDiff.ah1.
6. In \diff\lib\Exo, rename FileObject.ahk, WB_onKey.ahk and API.ahk as FileObject.ah1, WB_onKey.ah1 and API.ah1 respectively.
7. In QuickConverterV2.ahk, replace two instances of `\diff\VisualDiff.ahk` with `\diff\VisualDiff.ah1`.
8. In QuickConverterV2_scintilla.ahk, replace two instances of `\diff\VisualDiff.ahk` with `\diff\VisualDiff.ah1`.

### CODE REVIEW

**Comment by Banaanae** [comment]
> For clarity within the source, consider using the ah1 ext for all v1 code, and the ah2 ext for all v2 code. This also helps with some compatibility issues with some of the extensions/addons of particular IDEs.

We use `.ahk` for all source files, `#Requires ` shows the version
`.ah1` and `.ah2` are only used for tests.
@andymbody do you have any opinions on this?

> In \diff\VisualDiff.ahk, replace "_AHKv1v2_\d{10}\.ahk$" with "_AHKv1v2_\d{10}\.(ahk)|(ah1)$", otherwise, if srcFilePath has an ah1 extension, it won't be deleted on exit.

`.ahkl` should also be added

**Comment by Banaanae** [comment]
> In \diff\lib\Exo, rename FileObject.ahk, WB_onKey.ahk and API.ahk as FileObject.ah1, WB_onKey.ah1 and API.ah1 respectively.

I should note that I have started updating these files to v2 locally, just figuring out complex code + converter bugs

**Comment by fade2gray** [comment]
I was considering converting VisualDiff to V2 myself, seems you beat me to it.

I started with ...

changing VisualDiff...
```ahk
StringReplace, htmlcontents, htmlcontents, exo_lhsvalue_placeholder, %lhsvalue%
StringReplace, htmlcontents, htmlcontents, exo_rhsvalue_placeholder, %rhsvalue%
StringReplace, htmlcontents, htmlcontents, exo_file1name_placeholder, %file1name%
StringReplace, htmlcontents, htmlcontents, exo_file2name_placeholder, %file2name%
StringReplace, htmlcontents, htmlcontents, exo_instructions_placeholder, %instructions%
```
to ...
```ahk
htmlcontents := StrReplace(htmlcontents, exo_lhsvalue_placeholder, %lhsvalue%, 0, &OutputVarCount)
htmlcontents := StrReplace(htmlcontents, exo_lhsvalue_placeholder, %rhsvalue%, 0, &OutputVarCount)
htmlcontents := StrReplace(htmlcontents, exo_lhsvalue_placeholder, %file1name%, 0, &OutputVarCount)
htmlcontents := StrReplace(htmlcontents, exo_lhsvalue_placeholder, %file2name%, 0, &OutputVarCount)
htmlcontents := StrReplace(htmlcontents, exo_lhsvalue_placeholder, %instructions%, 0, &OutputVarCount)
```
... it converts as ...
```ahk
htmlcontents := StrReplace(htmlcontents, exo_lhsvalue_placeholder, %lhsvalue%, , &OutputVarCount, -1)
htmlcontents := StrReplace(htmlcontents, exo_lhsvalue_placeholder, %rhsvalue%, , &OutputVarCount, -1)
htmlcontents := StrReplace(htmlcontents, exo_lhsvalue_placeholder, %file1name%, , &OutputVarCount, -1)
htmlcontents := StrReplace(htmlcontents, exo_lhsvalue_placeholder, %file2name%, , &OutputVarCount, -1)
htmlcontents := StrReplace(htmlcontents, exo_lhsvalue_placeholder, %instructions%, , &OutputVarCount, -1)
```

**Comment by andymbody** [comment]
> andymbody, do you have any opinions on this?

I have no specific opinion regarding file extensions. I personally use ahk regardless of version. I haven't really considered the pros/cons of the other extensions.

**Comment by Banaanae** [comment]
> I was considering converting VisualDiff to V2 myself, seems you beat me to it.

Please also give it a try! Updating the exo api isn't very easy :) We probably should change the lib to [AutoHotkey-jk](https://github.com/Lexikos/AutoHotkey-jk)

**Comment by Banaanae** [comment]
Update on V2 conversion
Diffing sort of works, but is successfully running on ahk-jk

**Pull request closed without merging**
