### PR TITLE
Add Include Failing option

### PR DESCRIPTION
**Pull request by Banaanae**
This adds the ability to include failing tests in Testmode, currently
- Only QuickConvertorV2.ahk works (I'll do _scintilla once there aren't any bugs left)
- The check doesn't persist between reloads

The way it currently works is if Include failing is on, it will change the `AddSubFoldersToTree` folder from `TreeRoot` to `A_ScriptDir "/tests"`, one downside is `/Yunit/doc/` now show in the tree while Include Failing is on, but since there are no .ah1 file in there it shouldn't cause any issues

### CODE REVIEW

**Comment by mmikeww** [comment]
I ticked the checkbox, and then clicked the "Eval Tests" button at the bottom, but nothing changed. But then when I reloaded, it did include the failed tests correctly

Maybe on each toggle of that checkbox, we auto reload, as an easy workaround?

**Comment by Banaanae** [comment]
> Maybe on each toggle of that checkbox, we auto reload, as an easy workaround?

Maybe something like this?
image

**Comment by mmikeww** [comment]
That's fine too

**Comment by Banaanae** [comment]
Nevermind _scintilla still needs work

**Comment by mmikeww** [comment]
i dont care about the scintilla part, but is this otherwise ready for merge?

**Pull request merged**
