### PR TITLE
Fix extra (unnecessary) CRLFs

### LINKED ISSUE #193: Unneccessary trailing newlines in label conversion and at end of files
### This does not affect scripts abilities to run afaik
Unsure why this is happening, would be nice to get this fixed as it can cause a mess in scripts

Consider `Menu_ex7.ah1`'s conversion (in failing tests):
image
It creates so many newlines that I can't even fit them all in the screenshot!
The causes seem pretty specific as well (but common enough where it happens in normal scripts)

For EOF example see `Menu_cbFunc_01.ah1`

### PR DESCRIPTION
**Pull request by andymbody**
Fix #193 (unnecessary CRLF's) when converting labels to functions

### CODE REVIEW

**Comment by Banaanae** [comment]
Nice!
There is one side effect that comes with this, but I'll leave it up to you if we should fix this or just merge as is.
Any trailing newlines in the source script now also get removed
image
Shouldn't be too much of an issue however (and IMO much better than what was happening before)

**Comment by Banaanae** [comment]
My commits just remove a trailing newline that wasn't present in the converted code

**Comment by andymbody** [comment]
>There is one side effect that comes with this...

I have fixed this issue if you want to include it... But I don't know how to edit a commit to reflect new changes. I would have to submit an alternate PR.

Do you want me to do this?

**Comment by mmikeww** [comment]
You have some options here. 1. You could just add another commit on top to
this PR branch. Multiple commits are fine. And then if Bananne thinks they
are redundant then he can squash them all into one commit when he makes the
merge into the main repo. Or 2. You could edit your previous commit locally
using `git reset` or what I prefer is to add the new commit on my local
machine and then use `git rebase -i` and do my own squash locally. But now
your local branch will deviate from your GitHub branch, and so you'll need
to do a force push `git push --force` in order to overwrite your remote
GitHub branch

**Pull request closed without merging**
