### PR TITLE
Fix some failed regex tests

### PR DESCRIPTION
**Pull request by andymbody**
Fixed all but 3 of the regex tests with this PR. Two more will be fixed with upcoming masking PR. Which leaves one left to do. (RegExMatch_issue_118-1 - It's a tricky one, and will require additional work.). Also related to #118.

Also rearranged/moved some of the test files for "better?" organization.

### CODE REVIEW

**Comment by andymbody** [comment]
Will this PR require an edit if the previous PRs go thru first? How are "multiple pending PRs" handled by Git? My understanding is the a branch marks a particular point on the main/master "timeline". If multiple branches point to same/different points, what has to happen so that edits do not have to be performed between the time a commit is made and a PR is merged (when multiple others may be merged in between)?

**Comment by Banaanae** [comment]
They will only be problems if you changed the same line in both PRs, I'll merge the first one then we can see if this one is able to merge

**Comment by andymbody** [comment]
Ok... still don't understand this whole process but...

1. I updated my (online) main/master to reflect all (5) of the changes done in the last few hours.
2. Pulled those changes down to the local master
3. used SourceGit to "rebase" my local branches so that they reflect all changes up to date
4. this allowed my local branches to be in sync with the recent changes you made in last few hours (as if my local branches were created after the most recent changes you made).
5. (I think! lol)

Does this process sound like I did everything correct to get everything in sync?

I sure am glad I did not have to do all this on the command line. It would surely be messed up if the software did not "hold my hand" thru this process.

**Comment by mmikeww** [comment]
heres a visualization of what happened at each of your steps above
1:
```
mmikeww-github-----commit1--2--3--4--5---
     |                                   \
andy-github-------------------------------
```

2:
```
mmikeww-github-----commit1--2--3--4--5---
     |                                   \
andy-github-------------------------------
     |                                     \
andy-local-----------------------------------
```

3 before rebase:
```
mmikeww-github-----commit1--2--3--4--5---
     |                                   \
andy-github-------------------------------
     |                                     \
andy-local-----------------------------------
     |                                     
andy-feature--commit1--2-
```

3 after rebase:
```
mmikeww-github-----commit1--2--3--4--5---
     |                                   \
andy-github-------------------------------
     |                                     \
andy-local-----------------------------------
                                             \
                                              andy-feature-----commit1--2--
```

you can confirm on your machine if the history is correct by using tools such as `git log` or `gitk` or whatever gui your sourcegit tool shows. just checkout the feature branch and confirm the history that its built on top of to ensure the history is correct

if it matches what i've drawn, then yes, if you now push your feature branch to your github, and then start a PR for it, then yes it will just be built on top of the previous 5 changes, and everything should be fine

if you did not rebase, you could still submit a PR, but there might be conflicts, for example if the same lines were changed in your feature commits, and the commits1-5 from mmikeww-master. then the PR would show conflicts that need to be resolved before the PR can merge smoothly. 

when you do the rebase on your local machine, git will notify you at that time if there are conflicts, and then you are forced to fix the conflicts yourself before the rebase will even succeed. in both cases, the conflicts need to be resolved anyway before a merge can succeed, so thats why i tend to just rebase locally anyway to save everyone the trouble in advance. since i know the code best since i wrote it, i'm probably in the best position to resolve the conflicts. submitting a PR first that might have conflicts will just waste other people's time who aren't as familiar with the changes that you are proposing

of course, if its a deeper change, or in a more public project that is larger and has much more scrutiny on the code, perhaps you would WANT to submit the PR with conflicts and get advice or stimulate discussion as to whether or not thats the best way to implement the changes. say for example if you were suggesting a PR to the linux kernel or something. they probably aren't going to be as loose to blindly merge code as we are in here

**Comment by andymbody** [comment]
> when you do the rebase on your local machine, git will notify you at that time if there are conflicts

Thank you for all your help/details and the visuals. I really appreciate your efforts to educate me with this. I think the result looks/acts like what you have drawn. And I would imagine that the sw would have warned me if there were conflicts.

**Comment by mmikeww** [comment]
You can test it yourself. Checkout master and create a new branch called
test1. Commit a msg box hello world. Then checkout back to master and
create a new branch test 2. Commit another msg box in the same spot with a
different message. Then try to rebase test2 onto test1. Git should give you
a conflict

**Comment by andymbody** [comment]
> You can test it yourself

Ok... will do.... Thanks!

**Comment by andymbody** [comment]
> They will only be problems if you changed the same line in both PRs

Ah... ok... so it doesn't overwrite the files with the entire PR... just updates a changed file with portions that are different? I guess this makes sense. I was thinking a complete overwrite took place.

**Pull request merged**
