### PR TITLE
Updated to Ahk V2 Beta

### PR DESCRIPTION
**Pull request by dmtr99**
Updated to AHK V2 Beta, this seems to work, but I could not convert ConvertFuncs.ahk fully

### CODE REVIEW

**Comment by mmikeww** [comment]
Cool thanks... looks like this only updates the converter script itself to v2beta. I imagine most people will be looking for the actual conversion functionality to work from v1 -> v2-beta, which obviously is a much larger job. Right now this thing is only converting v1 -> v2-a087 or something way outdated. I don't know if we should wait and merge this and that all at once

**Comment by dmtr99** [comment]
Yes, and currently ConvertFuncs.ahk is still not working, I would suggest to first convert it to V2 Beta and then we can start testing and improving it bit by bit. But I got a lot of error messages when I tried to convert it. I decided to first work on setting up AHK studio for v2 beta syntax, and I have made a launcher that automatically detects and runs the correct version of the script, so I can mix V1 and V2 for the moment. ConvertFuncs.ahk is quite high level coding, so I did not understood it fully, but impressive and great to learn from. I`ll add my legacy IsFunc function that I made, as it is removed from V2.

**Comment by mmikeww** [comment]
yes those ConvertFuncs were originally authored by Frankie here:
https://autohotkey.com/board/topic/65333-v2-script-converter/

and then I just updated them as I went along to try to add more features

keeping this thing up to date is very time consuming, and thats why I stopped working on it. But I agree that it would be hugely beneficial as v2 becomes more mainstream

**Comment by mmikeww** [comment]
yeah so it looks like most of your changes were already done in this commit from the `v2updates` branch:

https://github.com/mmikeww/AHK-v2-script-converter/commit/6972e7538e4b35a3d4fca9f776fdd76429c2aba1

the only thing missing is that the obj properties like `.Length` were being called as funcs (`.Length()`) in that commit

**Pull request merged**
