### PR TITLE
Fix for issue #131 - Add func param for menu callback

### LINKED ISSUE #136: OnMessage errors
AHK v1 code:
(modified example of OnMessage example no.1)
```ahk
Gui, Add, Text,, Click anywhere in this window.
Gui, Add, Edit, w200 vMyEdit
Gui, Show
OnMessage(0x0201, "WM_LBUTTONDOWN")
return

WM_LBUTTONDOWN(wParam, lParam)
{
    X := lParam & 0xFFFF
    Y := lParam >> 16
    if A_GuiControl
        Ctrl := "`n(in control " . A_GuiControl . ")"
    ToolTip You left-clicked in Gui window #%A_Gui% at client coordinates %X%x%Y%.%Ctrl%
}

F5::
Tooltip
OnMessage(0x0201, "")
Return

GuiClose:
ExitApp
```

Expected v2 code:
```ahk
MyGui := Gui()
MyGui.Add("Text",, "Click anywhere in this window.")
MyGui.Add("Edit", "w200")
MyGui.Show
OnMessage 0x0201, WM_LBUTTONDOWN

WM_LBUTTONDOWN(wParam, lParam, msg, hwnd)
{
    X := lParam & 0xFFFF
    Y := lParam >> 16
    Control := ""
    thisGui := GuiFromHwnd(hwnd)
    thisGuiControl := GuiCtrlFromHwnd(hwnd)
    if thisGuiControl
    {
        thisGui := thisGuiControl.Gui
        Control := "`n(in control " . thisGuiControl.ClassNN . ")"
    }
    ToolTip "You left-clicked in Gui window '" thisGui.Title "' at client coordinates " X "x" Y "." Control
}

F5:: {
Tooltip
OnMessage(0x0201, WM_LBUTTONDOWN, 0)
}
```

Generated Code:
```ahk
myGui := Gui()
myGui.OnEvent("Close", GuiClose)
myGui.Add("Text", , "Click anywhere in this window.")
ogcMyEdit := myGui.Add("Edit", "w200 vMyEdit")
myGui.Show()
OnMessage(0x0201, WM_LBUTTONDOWN)
return

WM_LBUTTONDOWN(wParam, lParam) ; also needs msg, hwnd
{
    X := lParam & 0xFFFF
    Y := lParam >> 16
    if A_GuiControl ; 
        Ctrl := "`n(in control " . A_GuiControl . ")"
    ToolTip("You left-clicked in Gui window #" A_Gui " at client coordinates " X "x" Y "." Ctrl)
}

F5::
{ ; V1toV2: Added bracket
ToolTip()
OnMessage(0x0201) ; Should be OnMessage(0x0201, WM_LBUTTONDOWN, 0)
Return
} ; Added bracket before function

GuiClose(*)
{ ; V1toV2: Added bracket
ExitApp()

} ; Added bracket in the end
```

### PR DESCRIPTION
**Pull request by andymbody**
Fix for issue #131. ~Will now add * param to functions for menu callbacks.~ Also made a couple adjustments to MaskCode.ahk (#213). Added commit to fix #136. Changed args from * to the 3 mentioned (for 131). Also fixed a bug that I introduced in my first commit. Also added commit to fix extra CR issue for files with CRLF line terminators.

### CODE REVIEW

**Comment by Banaanae** [comment]
Nice!
There's also issue #136, where OnMessage callbacks need `wParam, lParam, msg, hwnd`. Hopefully this will provide a base to implement this too

**Comment by andymbody** [comment]
> There's also issue..
Ok... will take a look when I can.

**Comment by andymbody** [comment]
> There's also issue..

Ok... will take a look when I can.

**Comment by andymbody** [comment]
This may be a repeat question, but... how would I change this current PR to include additional commits? I'm not ready to do that, but when I am I will need to know how. I will try to research it, but if there is a quick answer, I would appreciate any tips you may have.

**Comment by Banaanae** [comment]
So in your repository where you made your current changes, you should be able to make more changes, commit and push.

Sorry if it's not very descriptive :)
I can also merge this and then you can make the changes if needed

**Comment by andymbody** [comment]
> So in your repository where you made your current changes, you should be able to make more changes, commit and push.
> 
> Sorry if it's not very descriptive :) I can also merge this and then you can make the changes if needed

I think I know what you mean. I haven't researched yet, but i thought about it today and came up with the same possibility... just submit more commits on same branch... right?

I'm not sure how long it will take to add new commits so if you want to merge this now, that would be good. I can always get up to speed with multiple commits another time. Might do that with the next one, just to practice.

**Comment by Banaanae** [comment]
Also, rather than using `*` could we use `A_ThisMenuItem := "", A_ThisMenuItemPos := "", A_ThisMenu := ""`
Consider this:
```ahk
#Persistent
Menu, Tray, Add, My Menu Item, MyHandlerFunc


MyHandlerFunc() {
	MsgBox % A_ThisMenuItem     ; My Menu Item
	MsgBox % A_ThisMenuItemPos  ; 1
	MsgBox % A_ThisMenu         ; Tray
}
```
```ahk
Persistent
Tray:= A_TrayMenu
Tray.Add("My Menu Item", MyHandlerFunc)


MyHandlerFunc(A_ThisMenuItem := "", A_ThisMenuItemPos := "", A_ThisMenu := "") {
	MsgBox(A_ThisMenuItem)     ; My Menu Item
	MsgBox(A_ThisMenuItemPos)  ; 11
	MsgBox(A_ThisMenu)         ; Error
}
```
With `*` there is a vars are undefined warning

Note 1) A_ThisMenuItemPos returns 1 in v1 and 11 in v2, I think this is because v1 returns the pos of the item ignoring default items, while v2 doesn't. I think we should keep it the same (not alter the variable, keep it at 11), it's more correct.

Note 2) A_ThisMenu fails, because it now returns the menu object instead of Menu name, (there doesn't appear to be any `Menu.Name`/`Menu.Title` properties, so it should be ok to leave as is, and maybe make a warning in the future)

**Comment by andymbody** [comment]
Ok... question...

should we worry about whether there are params already in the param list of the func? What should happen if we find that the func has params, but they have different names (other than A_ThisMenuItem, A_ThisMenuItemPos, or A_ThisMenu)? Will that ever be the case?

Should we just add the params you mention and wait to see if an "issue" is posted pointing out that these added params cause an issue?

I'm unfamiliar with Menu (I rarely/never use it), so forgive my ignorance if the answers to these questions are obvious.

**Comment by andymbody** [comment]
BTW... if i send an additional commit on this PR, I am moving post-convert operations to a dedicated function. This would be any conversion operations that are not within the actual loop of _convertLines(). There were only a couple until recently (placed at the bottom of _convertLines()), but they are growing and I think they deserve their own function/organization for code clarity. The dedicated function will be place just below _convertLines() func.

Sound ok to you?

**Comment by Banaanae** [comment]
> should we worry about whether there are params already in the param list of the func?

I think we still put the A_ThisMenu* params first, then the user defined params with a warning like `; V1toV2: Update function calls to make [param name] fourth`

> What should happen if we find that the func has params, but they have different names (other than A_ThisMenuItem, A_ThisMenuItemPos, or A_ThisMenu)? Will that ever be the case?

These are built in variables (like `A_ThisFunc` and `A_ThisHotkey`), they used to behave like those, and now they can only be accessed via a menu callback (like `A_GuiEvent`). We won't need to worry about this happening

> Should we just add the params you mention and wait to see if an "issue" is posted pointing out that these added params cause an issue?

Probably not best practice, but this is what I have been doing :)
Hopefully if an issue does get reported we might have a better idea on how to handle these situations, (personally, seeing how this code is used in the wild is the best way to fix stuff like this, and in the wild most scripts use labels)

> Sound ok to you?
Sounds great

**Comment by andymbody** [comment]
Added commit for fix of #136. The software showed an error and that the commit did not upload. But it looks like it did. Some of the edited code in this commit changed code in the original commit. So, let me know if I need to resubmit the entire PR.

**Comment by Banaanae** [comment]
I see the commit too

Do you have plans on fixing the points listed in my prior post? Or should I transfer the comment to an issue

**Comment by andymbody** [comment]
Included another commit to prevent extra CR added for files that have line terminators of CRLF. I'm not sure when this was introduced, but it doesn't look recent. This issue was caused by parse-loop in UpdateGoto().

I think that's enough commits for this one... Starting to included edits that are unrelated to original commit. But it gave me some practice with updating PR with new commits.

**Comment by andymbody** [comment]
Included another commit to prevent extra CR added for files that have line terminators of CRLF. Introduced on 6/15 with UpdateGoto().

I think that's enough commits for this one... Starting to included edits that are unrelated to original commit. But it gave me some practice with updating PR with new commits.

**Pull request merged**
