### PR TITLE
Fix for #183

### PR DESCRIPTION
**Pull request by andymbody**
Fix for #183 + test files

### CODE REVIEW

**Comment by andymbody** [comment]
I finally found a nice GUI that makes this process so much easier! [SourceGit](https://github.com/sourcegit-scm/sourcegit/releases/tag/v8.15)

**Comment by kiwichick888** [comment]
What I found is that it wasn't missing, it was that the closing brace was being put in the wrong place. So, in my script that you've been referencing, instead of placing the closing brace after the Reload command, the converter was placing it at the end of the script.

**Comment by andymbody** [comment]
> the closing brace for Reload was placing it at the end of the script.

I know it appeared that way, but that was a different closing brace at the end of the script. You'll notice that the brace was labeled 

The closing brace for the function would be labeled 
} ; V1toV2: Added bracket

But instead what you had was 2 of these at the end. This is placed by a different part of the loop
} ; V1toV2: Added bracket in the end

So the correct closing brace was missing, and the end brace was being placed twice.

**Comment by andymbody** [comment]
> the closing brace for Reload was placing it at the end of the script.

I know it appeared that way, but that was a different closing brace at the end of the script.

The closing brace for the function would be labeled like this...
} ; V1toV2: Added bracket

But instead what you had was 2 of these at the end. This is placed by a different part of the loop
} ; V1toV2: Added bracket in the end

So the correct closing brace for Reload was missing, and the end brace was being placed twice.

**Comment by andymbody** [comment]
> the closing brace for Reload was placing it at the end of the script.

I know it appeared that way, but that was a different closing brace at the end of the script.

The closing brace for the function would be labeled like this...
} ; V1toV2: Added Bracket before label

But instead what you had was 2 of these at the end. This is placed by a different part of the loop
} ; V1toV2: Added bracket in the end

So the correct closing brace for Reload was missing, and the end brace was being placed twice.

**Comment by kiwichick888** [comment]
> So the correct closing brace for Reload was missing, and the end brace was being placed twice.

Ah I see, different interpretations of what was going on - and my interpretation was wrong 😆

**Comment by andymbody** [comment]
> Ah I see, different interpretations of what was going on

I thought the same thing until I investigated further into the cause. Then the true issue became clear.

The comments on the braces are a little misleading as well until the loop is inspected.

**Comment by andymbody** [comment]
> Ah I see, different interpretations of what was going on

I thought the same thing until I investigated further into the cause. Then the true issue became clear.

The comments on the braces are a little misleading as well until the loop is inspected. I think they should be labeled "opening brace", "closing brace" so it is clear in the final script. And each time I see them, I want to change the comment/label but I will try to ignore the urge. lol

**Comment by kiwichick888** [comment]
> The comments on the braces are a little misleading as well until the loop is inspected. I think they should be labeled "opening brace", "closing brace" so it is clear in the final script. And each time I see them, I want to change the comment/label but I will try to ignore the urge. lol

I absolutely agree.

**Pull request merged**
