### PR TITLE
Fix case (Fileread → FileRead)

### PR DESCRIPTION
**Pull request by Ragnar-F**

### CODE REVIEW

**Comment by Banaanae** [comment]
Tests will need updating, I'll do that and merge when I get home

**Comment by Banaanae** [comment]
Turns out tests aren't affected by case, might change that..

**Comment by andymbody** [comment]
> Turns out tests aren't affected by case, might change that..

Do you feel it will provide valuable payback for the effort? When most (all?) of AHK is not case sensitive?

**Comment by andymbody** [comment]
> Turns out tests aren't affected by case, might change that..

Do you feel the payback is worth the effort? When most (all?) of AHK syntax is not case sensitive? Would it be just a matter of changing '=' to '==' ? I haven't looked.

**Pull request merged**
