### PR TITLE
DropDownList and ComboBox fixes + new test

### PR DESCRIPTION
**Pull request by Banaanae**
- Added DropDownList alias DDL
- Removed Run_ex5 from failing tests because it passes and is present in Process/
- Make || act as choose if it isn't already present
- Make || not convert to "Option", "" (See below)
- Created a failing test for the below issues

## Known Issues

Choice is not correct with multiple "||"

In order to make || not become two options I convert any group of pipes to one | before the parse loop. Instead of pipes - 1 when two or more pipes. Both have pros and cons but the way I chose is definitely more common

### CODE REVIEW

**Comment by mmikeww** [comment]
thanks for your contribution, ill try to look at this today

**Comment by Banaanae** [comment]
Thanks! couple of changes not listed above
- Fix include tests (previously failing)
- Fix Menu's SetIcon (#138) and SetColor
- ControlGet_ex2.ah2 " Choose2" -> "Choose2" (side effect of double pipe fixes, still works)

Menu still needs work, I'll write more tests when i get the chance

I'd also like to get your opinion on either moving Failed Conversion to Test_Folder, or have an option to include failing under Testmode? Would make it easier to see how changes affect failing tests, and I can easily implement either one

eg
image

**Comment by mmikeww** [comment]
First, its preferable to keep different changes in different Pull Requests, so that they can be logically separated. These changes you've made are small, so its really no big deal. You've already done a great job by keeping each individual commit small and isolated, as well as the hugely important practice of added the test cases in the same commit, which is perfect. But its good to get into that habit of extending that same idea to PRs also, and just branching off for new changes. 

So, the workflow is usually to keep your 'master' branch clean and synced with the main repository, and then use `git checkout -b new_branch` to create a new branch and move to it, and then `git checkout master` to go back to the main branch. Then you could make changes to new_branch and create a PR just for that specific branch.

Anyway, can you give more detail about what you want to do with this?
> I'd also like to get your opinion on either moving Failed Conversion to Test_Folder, or have an option to include failing under Testmode? Would make it easier to see how changes affect failing tests, and I can easily implement either one

Can you explain what problem are we having now that we need to change it?

**Comment by mmikeww** [comment]
Oh I think I know what you mean... right now the known Failed Tests are not included in the test suite that gets run. And you'd like to add a checkbox to include running against them. Yes thats fine and thats a good idea.

Regarding git, you'll now notice that I've merged your PR, and the way github works is that it creates a merge commit, which means your master branch will look like its behind the main repo, even though the code is the same, because the merge commit is one commit ahead. You can get synced again by using the button on github website on your fork. If you wreck your repo you can just delete it from your github and then re-fork off.

But the idea is:

```
git checkout master        # moves you to your master branch that you should try to keep clean

git checkout -b issue123      # creates new branch issue123 and moves to it
git add..
git commit                  # make new commits/changes/etc to this branch
git push...               # push the changes from this branch to your github acct
# then you can create new PR for this branch only
```
I regularly create new branches just when i'm doing experimental work, so that I can keep the master branch clean. Any time I have a new idea I just branch off from master and start coding. Then I can always reformat stuff to clean it up later if I decide that that branch is worthy for public such as suggesting a PR

git is pretty powerful and so many answers are already available if you search. I'm a pretty basic user

**Comment by Banaanae** [comment]
Thanks for the feedback, I did consider new branches but wasn't sure if it would make merge conflicts. Probably just misunderstanding how it works though.

Now that this PR is closed I'll make sure to keep separate issues to different branches

Thanks again!

**Pull request merged**
