### PR TITLE
msgbox, menu, gui

### PR DESCRIPTION
**Pull request by dmtr99**
Improved Msgbox with continuation section and 1,3 and 4 parameter handling
Added start of Gui code
Added start of Menu code
Added mapkey xButton1 to test on the fly (just select code, pres XButton1, and you can test the v1 and v2 code)
Multiple changes, no break of previous defined tests

### CODE REVIEW

**Comment by mmikeww** [comment]
I know tabs vs spaces is a huge debate, but typically its preferable to stay with the status quo of the project, if for no other reason than to make it easy to view the changes. It looks like your text editor is using tabs for indentation, whereas this project is using spaces. And then in some spots, you are mixing between the two. Obviously its better if we stay consistent, and then it also makes it much easier to review the changes in the code. When I try to view these two PRs, its showing tons of lines got changed but some of then just simply modified the indentation to remove the spaces for tabs. Can you fix that and keep spaces instead so its easier to review?

**Comment by mmikeww** [comment]
Thanks for correcting the spaces vs tabs. Its much much easier to visually see the changes you've made on github forexample here:

https://github.com/mmikeww/AHK-v2-script-converter/pull/42/files

You still are using tabs for the Xbutton1 hotkey, and the Convert_GetContSect(), V1ParSplit(), and DebugWindow() functions. Ideally we want to keep everything consistent, so can you change those too? But at least I can much more easily go through the changes now.

I ran these changes against your Tests that you provided in the other PR. I did see the false positives as you call them. But in reality they are not false positives. It was because of what I mentioned on the AHK forums. the different between `` `n`` and `` `r`n`` . See here for the changes you need to make:
https://gist.github.com/mmikeww/6905fb7e6fd16477795bc1aaba99ef23/revisions

That still leaves one failing test, your `MsgBox1ParameterContinuationSection`. That just fails to convert properly.

**Comment by dmtr99** [comment]
Thanks for the review.

I have modified the code, but had not read your comments, so I will try to make the changes when I find the time.

Indeed, I will put the mapkeys in a separate script, this would be logical.
I have not yet implemented my , parser in the main command handler, then indeed I can clean up the handling of gui`s
I also added a test generator in my XButton1 hotkey, select code, press XButton1 and you can test the code in v1 and v2 and generate the test.

I will probably try to rename the output variable, as I need to modify it when the scripts discovers that a menu() that was defined should have been a menuBar(). If I make the variable output global, It should have a more specific name.

**Comment by mmikeww** [comment]
good stuff man, but its preferable if you use separate pull requests for each change... i see you added InputBox and FileSelect which are great additions, but you are starting to group everything together into one. i know youre new to git so just letting you know for future reference. its much cleaner to add each change individually.

**Comment by dmtr99** [comment]
OK, how do you prever that I proceed? This
Should we delete these pull requests and should I add them separately.
It is indeed quite complex if we are both working in the same file. And I am modifiing the general convert function.

I am indeed not familiar to github and added this to this pull request because this was the most simple.

**Comment by mmikeww** [comment]
I have no plans to work on the code anymore right now. I fixed everything from this main repo so now all of the existing tests pass for v2beta so I'm happy for now. I can help teach you git a little bit so that you can take over in whatever direction you are motivated, and you dont have to worry about me making conflicting changes.

As long as you don't delete the patch5 and patch6 branches in your personal repo, then these copies will remain.

Are you using the git command line? Or are you doing everything through the guis in VS Code and Github?

**Pull request closed without merging**
