### PR TITLE
General code Refactor - see description

### PR DESCRIPTION
**Pull request by andymbody**
Refactor of...
Global variable names (to identify global scope and var type at a glance)
Code organization - before/after _convertLines()
Fix regex needle bugs in MaskCode.ahk
Clean my messes
Changed any tabs to spaces (missed 3). I prefer tabs, but Mike said spaces should not be changed to tabs.
Also set one var to global by mistake, I was going to move it, but then decided not to and forgot to remove global keyword.

### CODE REVIEW

**Comment by andymbody** [comment]
Any comments about whether this will be accepted or not? I'm going to be pushing more commits but those are on top of the changes made here. Otherwise I will need to revert back and start from scratch with the other changes.  Let me know...

**Comment by Banaanae** [comment]
> Any comments about whether this will be accepted or not?

I will merge this, just wanted to see if you wanted to fix the `_SendMessage(p){` command, I might add this to #230, as that still needs changes before merging

**Comment by fade2gray** [comment]
@andymbody 

> Changed any tabs to spaces (missed 3). I prefer tabs, but Mike said spaces should not be changed to tabs.
You are aware that your [editor config](https://www.autoitscript.com/forum/topic/32588-scite-editor-how-to-make-tab-indentation-settings-permanent/?do=findComment&comment=234722) can set the keyboard tab key to use spaces instead of literal tabs - is this what’s causing the conflict [here](https://github.com/mmikeww/AHK-v2-script-converter/pull/231#issuecomment-2211611340)?

**Comment by andymbody** [comment]
> > Any comments about whether this will be accepted or not?
> 
> I will merge this, just wanted to see if you wanted to fix the `_SendMessage(p){` command, I might add this to #230, as that still needs changes before merging

I didn't see this post... and I was not aware there was anything wrong with that function. Will have to look. If you already fixed it, what was wrong? I got no errors on my end prior to submitting.

**Comment by andymbody** [comment]
> You are aware that...

I have made adjustments to my editor settings but this is not the only project I work on regularly. All my other projects use tabs. This is the only one that uses spaces, so it's a constant battle to keep switching tab/space formatting each time I move from one project to another. And I do this every few minutes. The easiest way to manage this is to set my settings to tab4 and do a mass convert from tabs to spaces prior to upload. But sometimes I forget to do this.

**Comment by fade2gray** [comment]
This is why I like using VSCode and its ability to use different workspaces for different projects. - you can change configurations on a per-workspace basis.

V1toV2

**Pull request merged**
