### PR TITLE
Fix #111

### LINKED ISSUE #111: Assignment line not translated well when using double quotes
This v1 line

`Clipboard := "Powershell -command ""Get-CimInstance -ClassName win32_operatingsystem | Select-Object CSName, LastBootUpTime | FT -Autosize"""`
is translated to v2 line
`A_Clipboard := "Powershell -command ""Get-CimInstance -ClassName win32_operatingsystem | Select-Object CSName, LastBootUpTime | FT -Autosize"""`
Must be using escaped quote otherwise it gives an autohotkey error
`A_Clipboard := "Powershell -command `"Get-CimInstance -ClassName win32_operatingsystem | Select-Object CSName, LastBootUpTime | FT -Autosize`""`

### PR DESCRIPTION
**Pull request by Banaanae**
This fixes #111, it replaces "" with `"
Accounts for any combination of vars and strings (see examples)

### CODE REVIEW

**Comment by mmikeww** [comment]
just been really busy but i will get to review these soon i hope

**Comment by andymbody** [comment]
There is a bug introduced with this update. The bug is now located in ConvertDblQuotes(). It strips the trailing portion of the line in some cases. Here is a test case to demonstrate the bug.

`strPos := (strPos=="") ? this._curPos : strPos`

becomes 

`strPos := strPos==""`

I have not looked into it further, but can if your time is limited.

Andy

**Comment by Banaanae** [comment]
Probably just an issue with the regexs, should be a quick fix

**Comment by andymbody** [comment]
Not the regex... I made a few edits and fixed in on my repo. Let me know whether you want me to submit a PR, or provide your own solution when you get time.

**Comment by andymbody** [comment]
Not the regex... I made a few edits and fixed in on my repo. Let me know whether you want me to submit a PR, or provide your own solution when you get time.

BTW... nice choice with the masking (functions). Implemented the same for the quote edits in my solution. I think it's the best solution for code clarity, yet avoid one edit from affecting another in the same line (no double-dipping).

**Comment by andymbody** [comment]
Not the regex... I made a few edits and fixed in on my repo. Let me know whether you want me to submit a PR, or provide your own solution when you get time.

BTW... nice choice with the masking (functions). Implemented the same for the quote edits in my solution. I think it's the best solution for code clarity, yet avoid one edit from affecting another in the same line (no double-dipping).

**Comment by andymbody** [comment]
Doesn't look like the regex... I made a few edits and fixed on my repo. Let me know whether you want me to submit a PR, or provide your own solution when you get time.

BTW... nice choice with the masking (functions). Implemented the same for the quote edits in my solution. I think it's the best solution for code clarity, yet avoiding one type of edit from affecting another in the same line. (no double-dipping!).

**Comment by andymbody** [comment]
Doesn't look like the regex... I made a few edits and fixed on my repo. Let me know whether you want me to submit a PR, or provide your own solution when you get time.

BTW... nice choice with the masking (functions). Implemented the same for the quote edits in my solution. I think it's the best solution for code clarity, yet preventing one type of edit from affecting another in the same line. (no double-dipping!).

**Comment by Banaanae** [comment]
> BTW... nice choice with the masking (functions). Implemented the same for the quote edits in my solution. I think it's the best solution for code clarity, yet avoid one edit from affecting another in the same line (no double-dipping).

My fix was "borrowed" from your code :)

And yes please submit your fix, I'm currently sick and this is too complicated for my brain

**Comment by andymbody** [comment]
Oh wow... my brain is mush too when I'm sick. I will pray that you recover soon. 

Will submit the implementation. I also updated a couple of the regexs in the main loop, to narrow their focus. I didn't remove anything, just commented out the replaced code for now (until fully tested).

Get well!

**Pull request merged**
