### PR TITLE
Fix Typos

### PR DESCRIPTION
**Pull request by fade2gray**
Fix typos after adding opening and closing braces - `{` and `}` are braces, not brackets 😜.

### CODE REVIEW

**Comment by andymbody** [comment]
There are a whole lot of changes here that will undo recent commits. Were your changes made using the latest master?

**Comment by fade2gray** [comment]
Good catch. I forked the master and created a local clone, but I edited the file from the downloaded version from the forum link, copied it over the file in my clone and pushed it back to my fork.

I guess you can just drop the PR your end, and I'll submit another being more careful this time?

**Comment by Banaanae** [comment]
These changes are nice to have (anything to make script more clear), if you could resubmit with up-to-date changes I'll merge

**Comment by andymbody** [comment]
I guess while you're at it, might as well remove some commented out code that was left "just in case". I do like the date comments tho, cause I forget what was edited and why without having to perk into the project history. I personally think those comments provide benefit which browsing and editing the code. Is it helpful to any of you, or do you consider it clutter?

**Comment by Banaanae** [comment]
I'm fine with date comments, and yes most of the "just in case" code really isn't necessary like [here](https://github.com/mmikeww/AHK-v2-script-converter/blob/master/ConvertFuncs.ahk#L4087-L4138)
git stores all the changes ever made so _if_ we did need to go make it is stored there

GitHub allows maintainers to edit PR's so I should be able to clean up this just in case code and have fade2gray's fixes all in one commit

**Comment by andymbody** [comment]
> I'm fine with date comments, and yes most of the "just in case" code really isn't necessary like here 

Ok... I will try to do a better job cleaning up my messes. Sorry about that.

**Comment by Banaanae** [comment]
> Ok... I will try to do a better job cleaning up my messes. Sorry about that.

No worries, it was all commented out so it doesn't affect end user experience

**Comment by andymbody** [comment]
if @fade2gray doesn't clean up my mess with this commit, I will do it as part of my next submission.

**Pull request closed without merging**
