### PR TITLE
Update VarSetCapacity conversion

### PR DESCRIPTION
**Pull request by eugenesvk**
This converts `VarSetCapacity` to a `Buffer` even if `VarSetCapacity` is has arithmetic operations inlined , e.g.
v1 `VarSetCapacity(vTarget , RequestedCap, FillByte) // 4`
v2 `(vTarget:=Buffer(RequestedCap, FillByte)).Size // 4`
or
v1 `VarSetCapacity(vTarget , RequestedCap, FillByte)*0+&vTarget`
v2 `(vTarget := Buffer(RequestedCap, FillByte)).Size*0+&vTarget`

We've discussed all of the details of this change in the corresponding issue #53 , so won't repeat them here, will just note that the only thing missing is a user comment warning that even with 3 parameters (`FillByte`) the original intent might've been a string, not a buffer, so the user might want to user `VarSetStrCapactiy` instead

__Tests__: I've only added the file-based testing framework as that is a better system that's also easier to write/update tests for, also slightly improved it by adding a button allowing you to evaluate just 1 selected test instead of all of them

(fun fact: I've refactored my couple of tests from hard-coded strings in the `Tests.ahk` test suite to reading from files, then thought it'd be better looping through files rather than hard-coding their paths in the `Tests.ahk`, then remembered there is a different test suite, decided to finally look at it and realized it's already done this way, so thanks @dmtr99 for that)

### CODE REVIEW

**Comment by mmikeww** [comment]
I merged PR #56 so those changes broke the auto merge for yours, since you separated out the commands into their own files

**Comment by eugenesvk** [comment]
yeah, that's unfortunate

**Comment by mmikeww** [comment]
It looks like you're making lots of bigger changes... if you separated those changes into different branches, it would be easier to merge and compare the differences. But at this point it might just be better to merge all of your changes at once...

**Comment by eugenesvk** [comment]
Ok, so those commits only touched the commands, so wasn't that hard to rebase&redo them, think this should be fine now

**Comment by mmikeww** [comment]
Excellent work. 

If you plan on keep working on this, I can give you write access to the repository

**Comment by eugenesvk** [comment]
Thanks!
I might try to guard against a couple of no `{}` control flow blocks when v2 inserts a new line and maybe fix a function or two, but otherwise don't plan to touch the parser core
I'm fine merging the PRs myself, though as I mentioned in the other issue, another pair of eyes is always beneficial

**Comment by mmikeww** [comment]
I've added you, I think you just need to accept the invitation

You can still do work in your own brances in your own fork, and then still submit PRs here if you want someone else to review. But you've shown good git skills regarding commits and rebasing so I feel comfortable giving you access

**Pull request merged**
