### PR TITLE
Msgbox and Inputbox

### PR DESCRIPTION
**Pull request by SafetyCar**
A few more updates.

The MsgBox commit fixes an issue that I mentioned the other day.
Also introduces a new attached property into the arrays that get passed into custom functions. I put an object into the property so it can be expanded more easily hoping that things don't get too wild if it needs to get expanded.

### CODE REVIEW

**Comment by SafetyCar** [comment]
I've put a revert there. I could squash it with the related one, but I prefer to ask first.

**Comment by mmikeww** [comment]
> I've put a revert there. I could squash it with the related one, but I prefer to ask first.

Squashing it in your personal branch before the PR is merged is fine. Once the code gets merged to main repository, then we dont want to rewrite history. But I'll let you revert first before merging

**Comment by SafetyCar** [comment]
Ok, I think it's clean now. The last one was a about a yunit test that could be updated too.

**Comment by SafetyCar** [comment]
I just saw that an added test wouldn't show the title and I've fixed it.

**Comment by SafetyCar** [comment]
Please wait a bit more before merging I think I'll add some more tests later

**Comment by mmikeww** [comment]
Will do. Just let me know when its ready

**Comment by SafetyCar** [comment]
I think it's ready now. Added quite a mix of alternations in tests and seem to be producing the same results as v1.

**Pull request merged**
