### PR TITLE
Fix Ptr property

### PR DESCRIPTION
**Pull request by Banaanae**
Ran into problems when converting [this](https://www.autohotkey.com/board/topic/110808-getkeyname-for-other-languages/#entry682236)
This PR *should* fix it, but I'll leave it here for people to confirm if this is the correct conversion, and if any problems were introduced

### CODE REVIEW

**Comment by andymbody** [comment]
This is adding support of buffer object?

**Comment by Banaanae** [comment]
Yes-ish, buffer was already converted, put when you use a buffer in a pointer I'm pretty sure you need to add `.Ptr`, same with first parameter of StrGet (and maybe StrPut?)

**Comment by andymbody** [comment]
Just my opinion... I would say if it works, should be acceptable. I might have code in my library to test it on, but would take too long to find it. If an issue arises in the future, it can be addressed then.

**Comment by Banaanae** [comment]
It appears all instances of
`&BufferObj` need to be replaced with `BufferObj.Ptr` no matter location
This will probably be closed and replaced with new fix

**Pull request closed without merging**
