### PR TITLE
fix hotkeys with special chars

### PR DESCRIPTION
**Pull request by andymbody**
IF-Refactor and partial update for continued label conversion (#236).
(Label conversion support is being done in stages)

~(forgot to cleanup commented-out code prior to submitting this - will perform cleanup as part of next PR)~.

Added commits to clean up mess.
Added tests for newly supported hotkeys, moved hotkey tests to appropriate folder

READY FOR MERGE - I don't plan to add any more commits to this PR

### CODE REVIEW

**Comment by Banaanae** [comment]
> (Label conversion support is being done in stages)

Great way to approach changes like this, I'll test and merge soon

**Comment by andymbody** [comment]
> I'll test and merge soon

Curious... when you say test... can you elaborate what that involves on your end? Is there more testing I should be doing prior to submitting the PRs? Do you have workflows that might be helpful on my end as a beginner?

**Comment by mmikeww** [comment]
From my perspective, "testing" should just be the merger running the full
test suite to ensure nothing is broken, in case the PR submittor forgot to
run those tests themselves to check for regression bugs. That's why it's
essential to always keep the test suite up to date

**Comment by andymbody** [comment]
> From my perspective, "testing" should just be the merger running the full test suite to ensure nothing is broken

Ok... that is my understanding as well. I will continue to do this.

**Comment by andymbody** [comment]
I just realized that I forgot to clean up my messes (commented-out code) with the PR. I will clean this up as part of my next PR.

**Comment by mmikeww** [comment]
It's preferable to clean up the additions in the same PR. You should be
able to simply add new commits to the same branch, and push them to your
repo

**Comment by andymbody** [comment]
> It's preferable to clean up the additions in the same PR. You should be able to simply add new commits to the same branch, and push them to your repo

Ah... thanks!. I didn't realize I could do this without causing a conflict... done!

**Comment by andymbody** [comment]
I have added the last commit for this PR. No more commits will be added.

**Comment by andymbody** [comment]
READY FOR MERGE - I don't plan to add any more commits to this PR

**Pull request merged**
